// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlrxvinipccjehetakqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRscnh2aW5pcGNjamVoZXRha3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzYxOTAsImV4cCI6MjA2MDM1MjE5MH0.ynW1AeimyYMr4NqVlfmweRXX1TBJ6EEUkss1hTCtwmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);